### PR TITLE
Smooth animation transition

### PR DESCRIPTION
**Pull request by jungsNN**
Made new animal fade in transition more smooth. 
#144 

https://user-images.githubusercontent.com/60561405/127908296-b9d7b09c-1176-4ab1-84dd-7e033b62f85b.mov

### CODE REVIEW

**Comment by jungsNN** [comment]
Also included a fix on animal card name centering:

_Before:_

FDB997E8-30BE-41AD-8120-2B3E5D13081F_4_5005_c

_After:_

E7F34781-2552-4929-B7E9-1F6D3C707AB2_4_5005_c

**Comment by bmalkmus** [comment]
https://drive.google.com/file/d/1uI0QDuf4WVhg59H2XAO9cnmcgzaPeO72/view

Reference 2:55 in this video. The Fade appears after the third crack/bounce of the egg, that is the target look. Is it possible to start the fading in of the animal at this point in the video?

**Comment by jungsNN** [comment]
Updated.

https://user-images.githubusercontent.com/60561405/127911294-c16df2fc-22fa-48c4-909f-9d743f40f548.mov

**Comment by bmalkmus** [comment]
looks good!

**Pull request merged**
